# Generated by Django 4.2.1 on 2023-06-02 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('investor', '0002_alter_investor_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestorOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annual_interest_rate', models.PositiveSmallIntegerField()),
                ('loan_period', models.IntegerField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Declined', 'Declined')], default='Pending', editable=False, max_length=10)),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='investor.investor')),
            ],
        ),
    ]
