# Generated by Django 4.2.1 on 2023-06-02 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investorOffer', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='investoroffer',
            table='Investor_Offer',
        ),
    ]
