# Generated by Django 4.2.1 on 2023-06-02 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Installment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateField()),
                ('amount', models.PositiveSmallIntegerField()),
                ('paid', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'installment',
            },
        ),
    ]
