# Generated by Django 4.2.1 on 2023-06-08 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('installment', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installment',
            name='due_date',
            field=models.DateTimeField(),
        ),
    ]
