# Generated by Django 4.2.1 on 2023-06-08 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('installment', '0003_alter_installment_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installment',
            name='amount',
            field=models.FloatField(),
        ),
    ]
