# Generated by Django 4.2.1 on 2023-06-08 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loanRequest', '0015_alter_loanrequest_table'),
        ('installment', '0004_alter_installment_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='installment',
            name='loan',
        ),
        migrations.AddField(
            model_name='installment',
            name='loan_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='loanRequest.loanrequest'),
            preserve_default=False,
        ),
    ]
