# Generated by Django 4.2.1 on 2023-06-08 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('installment', '0006_remove_installment_loan_id_installment_loan_request'),
    ]

    operations = [
        migrations.RenameField(
            model_name='installment',
            old_name='loan_request',
            new_name='loan',
        ),
    ]
