# Generated by Django 4.2.1 on 2023-06-01 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investor', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='investor',
            table='investor',
        ),
    ]
