# Generated by Django 4.2.1 on 2023-06-02 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('loanRequest', '0014_loanrequest_delete_loan'),
        ('loan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='loan_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='loanRequest.loanrequest'),
        ),
    ]
