# Generated by Django 4.2.1 on 2023-06-08 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0003_alter_loan_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='status',
            field=models.CharField(choices=[('Funded', 'Funded'), ('Delayed', 'Delayed'), ('Completed', 'Completed')], default='Funded', editable=False, max_length=10),
        ),
    ]
