# Generated by Django 4.2 on 2023-04-15 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loanRequest', '0002_borrower_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrower',
            name='type',
        ),
    ]
