# Generated by Django 4.2.1 on 2023-06-01 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loanRequest', '0008_remove_investor_user_remove_payment_loan_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='loan',
            table='loan',
        ),
    ]
