# Generated by Django 4.2.1 on 2023-06-02 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('borrower', '0002_alter_borrower_table'),
        ('loanRequest', '0013_alter_loan_loan_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_amount', models.IntegerField()),
                ('loan_period', models.IntegerField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Offered', 'Offered'), ('Funded', 'Funded')], default='Pending', editable=False, max_length=10)),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='borrower.borrower')),
            ],
            options={
                'db_table': 'LoanRequest',
            },
        ),
        migrations.DeleteModel(
            name='Loan',
        ),
    ]
