# Generated by Django 4.2.1 on 2023-06-02 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loanRequest', '0014_loanrequest_delete_loan'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='loanrequest',
            table='Loan_Request',
        ),
    ]
