# Generated by Django 4.2 on 2023-04-15 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0003_remove_borrower_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='investor',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='loans.investor'),
        ),
    ]
