# Generated by Django 4.2.1 on 2023-06-01 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('borrower', '0001_initial'),
        ('investor', '0001_initial'),
        ('loans', '0007_alter_loan_annual_interest_rate_alter_loan_lenme_fee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investor',
            name='user',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='loan',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='lenme_fee',
        ),
        migrations.AddField(
            model_name='loan',
            name='end_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='loan_total_amount',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='start_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='borrower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='borrower.borrower'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='investor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='investor.investor'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='loan_amount',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='loan_period',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Offered', 'Offered'), ('Funded', 'Funded'), ('Completed', 'Completed'), ('Delayed', 'Delayed')], default='Pending', max_length=10),
        ),
        migrations.DeleteModel(
            name='Borrower',
        ),
        migrations.DeleteModel(
            name='Investor',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
