# Generated by Django 4.2.1 on 2023-06-01 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0009_alter_loan_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Offered', 'Offered'), ('Funded', 'Funded'), ('Completed', 'Completed'), ('Delayed', 'Delayed')], default='Pending', editable=False, max_length=10),
        ),
    ]
